### PR TITLE
Include .tsx files in search

### LINKED ISSUE #4: Support *.tsx
Although `*.ts` files seem to run perfectly well, I'm having trouble getting `*.tsx` files to be recognised.

With `ava-ts **/*.test.{ts,tsx}` it claims it cannot find any `*.tsx` files, but finds an abundance of `*.ts` files and runs them successfully. I've tried renaming my `.tsx` files to `.ts`, and although `ava-ts` then finds them, it fails to compile &mdash; potentially because they now have an incorrect extension, or it may be an additional issue to resolve.

Do you have any examples of how to add support for `.tsx`?

### PR DESCRIPTION
**Pull request by DannyRyman**
Fixes #4
I think this important as I could find no other way to use Enzyme to test react components. Typescript does not allow you to include jsx in .ts files.

### CODE REVIEW

**Comment by andywer** [comment]
Thanks for your contribution, @DannyRyman!

Yeah, I agree. Let's support TSX, since otherwise it seems to be unnecessarily hard to test React code.

@Wildhoney Good news for you, in case you are still interested 😉

**Comment by Wildhoney** [comment]
Awesome @andywer &mdash; I'll party tonight like it's 1989 :confetti_ball:

(No seriously, it is useful for us &mdash; thanks guys!)

**Comment by andywer** [comment]
Awesome! :)

Will merge this PR, merge the original AVA `master` and release.
Might not make it today. If not, I will do it tomorrow!

**Comment by DannyRyman** [comment]
Brilliant. Thanks a lot!

**Comment by andywer** [comment]
Published as v0.24.1 🚀

**Pull request merged**
